services:
  db:
    image: postgres:15
    container_name: iphone_sales_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iphone_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iphone_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: iphone_sales_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:password@db:5432/iphone_db"
    ports:
      - "8000:8000"
    volumes:
      - .:/code

volumes:
  db_data: